---
title: "Graphs"
author: "Hannes Pieper"
date: "3/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
fig.path = 'markdown_figs'
```



```{r packages, echo = FALSE, message = FALSE}
# for creating the gif data frame as otherwise >50mb
library(dplyr)
library(tidyr)
library(stringr)
# plots
library(grid)
library(ggplot2)
# plots next to each other
library(ggpubr)
# packages for maps
library(rgdal)
library(rgeos)
library(mapproj)
# for gif
library(gganimate)
library(transformr)
```

```{r theme, echo = FALSE}

source("./scripts/themes.R")

```

```{r shape, echo = FALSE, message = FALSE, warning = FALSE, results = "hide"}
shp_bund <- readOGR("data/btw17-shapes/bundeslaender_small.shp",
  "bundeslaender_small",
  stringsAsFactors = FALSE,
  encoding = "latin1"
) %>%
  broom::tidy()


shp_wahlkreise <- readOGR("data/btw17-shapes/wahlkreise_small.shp",
  "wahlkreise_small",
  stringsAsFactors = FALSE,
  encoding = "latin1"
) %>%
  broom::tidy()
```


```{r graph_historic_size, echo = FALSE}
graph_historic_size <- read.csv("./data/graph_historic_size.csv")

# graph
graph_historic_size %>%
  ggplot(aes(x = `Jahr`, y = `Mandates`, group = 1)) +
  geom_line(aes(group = 1), color = "#009E73") +
  geom_hline(aes(yintercept = 598)) +
  scale_y_continuous(
    position = "right",
    limits = c(300, 820),
    breaks = c(300, 400, 500, 598, 700, 800),
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    breaks = sort(c(seq(1960, 2022, by = 10), 1949)),
    limits = c(1945, 2021),
    labels = c(
      "1949" = "1949", "1960" = "60", "1970" = "70",
      "1980" = "80", "1990" = "90", "2000" = "2000",
      "2010" = "10", "2020" = "20"
    ),
    expand = c(0, 0)
  ) +
  labs(
    title = "Historische Entwicklung der Größe des Bundestages",
    caption = "*Seit 2003\n Quelle: Bundeswahlleiter"
  ) +
  annotate("text",
    x = 1945, y = 800, label = "800 \nSitze",
    size = 2, color = "black", hjust = 0
  ) +
  annotate("text",
    x = 1945, y = 710, label = "700",
    size = 2, color = "black", hjust = 0
  ) +
  annotate("text",
    x = 1945, y = 598, label = "598 \n(Normgröße*)",
    size = 2, color = "black", hjust = 0
  ) +
  annotate("text",
    x = 1945, y = 510, label = "500",
    size = 2, color = "black", hjust = 0
  ) +
  annotate("text",
    x = 1945, y = 410, label = "400",
    size = 2, color = "black", hjust = 0
  ) +
  annotate("text",
    x = 1945.5, y = 350, label = "\u03df",
    size = 2, color = "black", hjust = 0
  ) +
  line_chart_theme()

# save graph
ggsave("./pictures/graph_historic_size.jpg", width = 4, height = 3)
```


```{r, distribution_graph, echo = FALSE, message = FALSE}
# read in data
graph_distribution <- read.csv("./data/graph_distribution.csv")

# graph
distribution <- graph_distribution %>%
  ggplot(aes(y = percent, x = `Gültige.Erststimmen`)) +
  geom_smooth(span = 0.1, color = "#009E73") +
  scale_x_continuous(
    breaks = c(seq(100000, 200000, 25000)),
    labels = c(
      "100000" = "100", "125000" = "125", "150000" = "150",
      "175000" = "175", "200000" = "200.000"
    )
  ) +
  scale_y_continuous(
    position = "right",
    limits = c(0, 1.05),
    breaks = c(seq(0.25, 1, 0.25)),
    expand = c(0, 0)
  ) +
  annotate("text",
    x = 210000, y = 1.025, label = "100%",
    size = 2, color = "black", hjust = 0.6
  ) +
  annotate("text",
    x = 210000, y = 0.975, label = "der Wahlkreise",
    size = 2, color = "black", hjust = 0.85
  ) +
  annotate("text",
    x = 210000, y = 0.775, label = "75",
    size = 2, color = "black", hjust = 0.2
  ) +
  annotate("text",
    x = 210000, y = 0.525, label = "50",
    size = 2, color = "black", hjust = 0.2
  ) +
  annotate("text",
    x = 210000, y = 0.275, label = "25",
    size = 2, color = "black", hjust = 0.2
  ) +
  labs(
    title = "Größe der Wahlkreise",
    subtitle = "nach abgegebenen gültigen Erststimmen oder weniger."
  ) +
  coord_cartesian(clip = "off") +
  line_chart_theme() +
  theme(
    axis.text = element_text(size = 5)
  )


# Distribution Graph  ---

# read in data
graph_margins <- read.csv("./data/graph_margins.csv")

# graph
margins <- graph_margins %>%
  ggplot(aes(y = percent, x = margin)) +
  geom_smooth(span = 0.1, color = "#009E73") +
  scale_y_continuous(
    limits = c(0, 1.05),
    breaks = c(seq(0.25, 1, 0.25)),
    expand = c(0, 0)
  ) +
  annotate("text",
    x = 73500, y = 1.025, label = "100%",
    size = 2, color = "black", hjust = 0.65
  ) +
  annotate("text",
    x = 73500, y = 0.975, label = "der Wahlkreise",
    size = 2, color = "black", hjust = 0.85
  ) +
  annotate("text",
    x = 73500, y = 0.775, label = "75",
    size = 2, color = "black", hjust = 0.2
  ) +
  annotate("text",
    x = 73500, y = 0.525, label = "50",
    size = 2, color = "black", hjust = 0.2
  ) +
  annotate("text",
    x = 73500, y = 0.275, label = "25",
    size = 2, color = "black", hjust = 0.2
  ) +
  scale_x_continuous(
    breaks = c(seq(0, 70000, 17000)),
    labels = c(
      "0" = "0", "17000" = "17", "34000" = "34",
      "51000" = "51", "70000" = "70.000"
    )
  ) +
  labs(
    title = "Abstand Erst- und Zweitwahl nach Erststimme",
    subtitle = "kummulierten Abstand oder weniger."
  ) +
  coord_cartesian(clip = "off") +
  line_chart_theme() +
  theme(
    axis.text = element_text(size = 5)
  )


# combine graphs margin and distribution size ---

figure <- ggarrange(margins, distribution,
  ncol = 2, nrow = 1,
  common.legend = FALSE
)

figure <- annotate_figure(figure,
  bottom = text_grob("Quelle: Bundeswahlleiter \nEigene Berechnungen",
    color = "#3B3B3B",
    hjust = 1, x = 0.98,
    size = 4
  ),
)

figure <- figure + bgcolor("#F0F0F0")
figure

# save graph
ggsave("./pictures/graph_margins_distribution.jpg", width = 4, height = 3)
```



```{r election_map_2017, echo = FALSE, message = FALSE}
# read in data
map_actual_election <- read.csv("./data/map_actual_election.csv")

# map
map_actual_election %>%
  ggplot(aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Partei),
               show.legend = T
  ) +
  geom_polygon(
    data = shp_wahlkreise,
    aes(x = long, y = lat, group = group),
    fill = NA,
    color = "white",
    size = 0.025
  ) +
  geom_polygon(
    data = shp_bund,
    aes(x = long, y = lat, group = group),
    fill = NA, color = "white", size = 0.1
  ) +
  scale_fill_manual(values = c(
    "blue4", "#32302e", "royalblue1",
    "#46962b", "magenta1", "#E3000F"
  )) +
  labs(
    title = "Direktmandate Bundestagswahl 2017",
    caption = "Quelle: Bundeswahlleiter"
  ) +
  coord_map() + # apply projection
  map_theme()

# save map
ggsave("./pictures/map_actual_election.jpg", width = 2, height = 2.7)
```


```{r optimized_map_2017, echo = FALSE, message = FALSE}
# read in data
map_optimized_election <- read.csv("./data/map_optimized_election.csv")

# map
ggplot(data = map_optimized_election, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = change), show.legend = T) +
  geom_polygon(
    data = shp_wahlkreise,
    aes(x = long, y = lat, group = group),
    fill = NA,
    color = "white",
    size = 0.025
  ) +
  geom_polygon(
    data = shp_bund,
    aes(x = long, y = lat, group = group),
    fill = NA, color = "white", size = 0.1
  ) +
  scale_fill_manual(
    values = c(
      "blue4", "#32302e", "royalblue1",
      "#46962b", "magenta1", "#E3000F"
    ),
    name = "Neues Direktmandat",
    na.translate = F
  ) +
  labs(
    title = "Direktmandate nach Stimmenverschiebung",
    caption = "Quelle: Bundeswahlleiter \nEigene Berechnungen"
  ) +
  coord_map() + # apply projection
  map_theme()

# save map
ggsave("./pictures/optimized_election_map_pic.jpg", width = 2, height = 2.7)
```

```{r gif, echo = FALSE, message = FALSE}

# read in data
map_optimized_election <- read.csv("./data/map_optimized_election.csv")
map_gif <- read.csv("./data/map_gif.csv")
graph_dynamic_size <- read.csv("./data/graph_dynamic_size.csv")

# create combination for each county with each number of votes ('states')
# of the gif
gif <- map_gif %>%
  select(Wahlkreisnummer) %>%
  mutate(
    "1" = "0",
    "2" = 20000,
    "3" = 40000,
    "4" = 60000,
    "5" = 80000,
    "6" = 100000,
    "7" = 120000,
    "8" = 140000,
    "9" = 160000,
    "10" = 180000,
    "11" = 200000,
    "12" = 220000,
    "13" = 240000
  ) %>%
  gather(2:14, key = tmp, value = Votes) %>%
  mutate(Votes = as.numeric(Votes)) %>%
  select(-c("tmp")) %>%
  mutate(size = 709) %>%
  mutate(
    size = replace(size, Votes == "20000", 700),
    size = replace(size, Votes == "40000", 700),
    size = replace(size, Votes == "60000", 685),
    size = replace(size, Votes == "80000", 685),
    size = replace(size, Votes == "100000", 671),
    size = replace(size, Votes == "120000", 654),
    size = replace(size, Votes == "140000", 625),
    size = replace(size, Votes == "160000", 625),
    size = replace(size, Votes == "180000", 625),
    size = replace(size, Votes == "200000", 619),
    size = replace(size, Votes == "220000", 619),
    size = replace(size, Votes == "240000", 619)
  ) %>%
  full_join(., map_optimized_election)


# create data frame with all counties. Actual and optimized vote, cumulative
# votes and size parliament
gif <- graph_dynamic_size %>%
  filter(Wahlkreisnummer != "Election") %>%
  mutate(Wahlkreisnummer = as.numeric(Wahlkreisnummer)) %>%
  select(c(1, 8, 14)) %>%
  right_join(gif, by = "Wahlkreisnummer") %>%
  mutate(cummulative_votes = replace(
    cummulative_votes,
    is.na(cummulative_votes),
    0
  ))

# replace to NA if not a überhangmandate for given number of votes
# and also create text for the dynamic subtitle
gif <- gif %>%
  mutate(mandate_map = mandate_actual) %>%
  rowwise() %>%
  mutate(mandate_map = replace(
    mandate_map,
    cummulative_votes <= Votes,
    NA
  )) %>%
  mutate(mandate_map = replace(mandate_map, is.na(mandate_map), "white")) %>%
  mutate(mandate_map = as.factor(mandate_map)) %>%
  mutate(Votes = format(as.numeric(Votes), scientific = FALSE)) %>%
  mutate(States = as.character(Votes)) %>%
  mutate(States = paste(States, size, sep = ". Größe Bundestag: ")) %>%
  mutate(States = str_squish(States)) %>%
  mutate(States = str_replace(States, "0000", "0.000")) %>%
  mutate(States = str_replace(States, "10.0000", "100.000")) %>%
  mutate(States = str_replace(States, "20.0000", "200.000")) %>%
  mutate(States = replace(
    States,
    States == "100.000. Größe Bundestag: 709",
    "100.000. Größe Bundestag: 671"
  )) %>%
  mutate(States = replace(
    States,
    States == "200.000. Größe Bundestag: 709",
    "200.000. Größe Bundestag: 619"
  ))

# modify states as factors
level <- unique(gif$States)
gif$States <- factor(gif$States, levels = level)

# define colors for parties
Colors <- c(
  "CSU" = "royalblue1",
  "CDU" = "#32302e",
  "GRÜNE" = "#46962b",
  "LINKE" = "magenta1",
  "SPD" = "#E3000F",
  "AFD" = "blue4",
  "FDP" = "#ffed00",
  "white" = "white"
)


# gif graph layout
p_gif <- gif %>%
  ggplot(aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = mandate_map), show.legend = T) +
  geom_polygon(
    data = shp_wahlkreise,
    aes(x = long, y = lat, group = group),
    fill = NA, color = "#656565", size = 0.025
  ) +
  geom_polygon(
    data = shp_bund,
    aes(x = long, y = lat, group = group),
    fill = NA, color = "black", size = 0.1
  ) +
  scale_fill_manual(
    values = Colors,
    name = "Neues Direktmandat",
    na.translate = F
  ) +
  labs(
    title = "Überhangmandate",
    subtitle = "Wählerstimmen verändert: {closest_state}",
    caption = "Quelle: Bundeswahlleiter \n Eigene Berechnungen"
  ) +
  map_theme() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = rel(2.5),
                              face = "bold",
                              margin = unit(c(0, 0, 1.5, 0), "line")),
    plot.subtitle = element_text(size = rel(1.5),
                                 hjust = 0.5,
                                 margin = unit(c(0, 0, -1, 0), "line")),
    plot.caption = element_text(size = rel(1))
  )

# add transition states
p_gif <- p_gif + transition_states(States,
  transition_length = 5,
  state_length = 40
)

# render gif
animate(p_gif, height = 800, width = 800)

# save gif
anim_save("./pictures/dynamic_map.gif", width = 2, height = 2.7)
```
